[package]
name = "messagepack"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rmp-serde = { version = "1.1.0", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }
